# Generated by Django 5.2.9 on 2025-12-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_rating_created_date_alter_movieframe_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='country', to='movie_app.country'),
        ),
    ]
