# Generated by Django 5.2.9 on 2025-12-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='movie_app.country'),
        ),
    ]
